name: 'Run on Architecture'
branding:
  icon: 'cpu'
  color: 'green'
description: 'Run commands in a Linux container with a specific architecture (amd64,arm64,armv7,i386,ppc64le,s390x)'
author: 'Umberto Raimondi'
inputs:
  architecture:
    description: 'Architecture type: amd64,arm64,armv7,i386,ppc64le,s390x'
    required: false
    default: 'amd64'
  run:
    description: 'Command/s to execute'
    required: true
runs:
  using: 'node12'
  main: 'src/run-on-arch.js'
